default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: blog5_development

test: &test
  <<: *default
  database: blog5_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: blog5_production

cucumber:
  <<: *test